#!/bin/sh -e
# Swarm gives you the node ID at deploy-time; we pass it in NODE_ID
NODE_NAME=$(cat /etc/nodename)
echo "node_meta{node_id=\"$NODE_ID\",node_name=\"$NODE_NAME\"} 1" \
     > /home/node-meta.prom        # this is the textfile collector dir
exec /bin/node_exporter \
     --collector.textfile.directory=/home "$@"
