global:
    scrape_interval: 15s
    evaluation_interval: 30s

scrape_configs:
    # Prometheus itself
    - job_name: prometheus
      static_configs:
          - targets: ['localhost:9090']

    # One target per Swarm node (dockerd metrics)
    - job_name: nodes
      dockerswarm_sd_configs:
          - host: unix:///var/run/docker.sock
            role: nodes
      relabel_configs:
          - source_labels: [__meta_dockerswarm_node_address]
            target_label: __address__
            replacement: $1:9323 # dockerd metrics port
          - source_labels: [__meta_dockerswarm_node_hostname]
            target_label: instance

    # All running tasks that have `prometheus-job` label
    - job_name: tasks
      dockerswarm_sd_configs:
          - host: unix:///var/run/docker.sock
            role: tasks
      relabel_configs:
          - source_labels: [__meta_dockerswarm_task_desired_state]
            regex: running
            action: keep
          - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
            regex: .+
            action: keep
          - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
            target_label: job
          - source_labels: [__meta_dockerswarm_task_address]
            target_label: instance
